=== TheDevTec/TheAPI/assembly.dtd
<!ELEMENT assembly (id,formats,includeBaseDirectory,dependencySets,moduleSets)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT formats (format)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT includeBaseDirectory (#PCDATA)>
<!ELEMENT dependencySets (dependencySet)>
<!ELEMENT dependencySet (outputDirectory,includes,unpack)>
<!ELEMENT outputDirectory (#PCDATA)>
<!ELEMENT includes (include+)>
<!ELEMENT include (#PCDATA)>
<!ELEMENT unpack (#PCDATA)>
<!ELEMENT moduleSets (moduleSet)>
<!ELEMENT moduleSet (useAllReactorProjects,includes,sources)>
<!ELEMENT useAllReactorProjects (#PCDATA)>
<!ELEMENT sources (includeModuleDirectory,fileSets)>
<!ELEMENT includeModuleDirectory (#PCDATA)>
<!ELEMENT fileSets (fileSet)>
<!ELEMENT fileSet (outputDirectory,excludes,directory,includes)>
<!ELEMENT excludes (exclude)>
<!ELEMENT exclude (#PCDATA)>
<!ELEMENT directory (#PCDATA)>

=== TheDevTec/TheAPI/assembly.xml
<!DOCTYPE assembly SYSTEM "assembly.dtd">
<assembly>
      <id>all</id>
      <formats>
        <format>jar</format>
      </formats>
      <includeBaseDirectory>false</includeBaseDirectory>
	  <dependencySets>
        <dependencySet>
            <outputDirectory>/</outputDirectory>
            <includes>
                <include>com.github.TheDevTec:TheAPI-Shared</include>
            </includes>
            <unpack>true</unpack>
        </dependencySet>
    </dependencySets>
      <moduleSets>
        <moduleSet>
          <useAllReactorProjects>true</useAllReactorProjects>
          <includes>
                <include>me.devtec.theapi.loaders:AdventureAPI</include>
                <include>me.devtec.theapi.loaders:BungeeAPI</include>
                <include>me.devtec.theapi.loaders:Shared-Fallback</include>
                <include>me.devtec.theapi.loaders:Loader-Bukkit-Legacy-Fallback</include>
                <include>me.devtec.theapi.loaders:Loader-Bukkit</include>
                <include>me.devtec.theapi.loaders:Loader-Bungee</include>
                <include>me.devtec.theapi.loaders:Loader-Velocity</include>
          </includes>
          <sources>
            <includeModuleDirectory>false</includeModuleDirectory>
            <fileSets>
              <fileSet>
                <outputDirectory>/</outputDirectory>
                <excludes>
                  <exclude>${project.build.directory}/**</exclude>
                </excludes>
				<directory>${project.build.directory}/classes</directory>
				<includes>
					<include>**/*.class</include>
					<include>**/*.yml</include>
					<include>**/*.json</include>
					<include>**/*.properties</include>
				</includes>
              </fileSet>
            </fileSets>
          </sources>
        </moduleSet>
      </moduleSets>
    </assembly>
